- name: "bug"
  color: "ee0701"
  description: "Indicates a confirmed issue or problem within the project."
- name: "dependencies"
  color: "555555"
  description: "Marks PRs related to dependency version updates."
- name: "docs"
  color: "c2e0c6"
  description: "Pertains to documentation of the project."
- name: "duplicate"
  color: "cccccc"
  description: "Marks an issue or pull request as a duplicate of another."
- name: "enhancement"
  color: "84b6eb"
  description: "Suggests new features or improvements to existing functionality."
- name: "future-maybe"
  color: "fef2c0"
  description: "Indicates potential ideas for future consideration."
- name: "good first issue"
  color: "7057ff"
  description: "Ideal for newcomers to the project, simpler issues to start contributing."
- name: "help wanted"
  color: "33aa3f"
  description: "Indicates a need for assistance on the issue or PR."
- name: "invalid"
  color: "e6e6e6"
  description: "Marks issues or PRs as irrelevant or inappropriate."
- name: "maintenance"
  color: "fbca04"
  description: "Denotes tasks focused on maintaining or improving existing codebase."
- name: "maybe-bug"
  color: "5fc1ce"
  description: "Something that might be a bug if more info is given."
- name: "needs more info"
  color: "31e0ab"
  description: "Requests additional information for clarification."
- name: "proposal"
  color: "1a388c"
  description: "Requested major feature or change of behavior."
- name: "question"
  color: "eaf961"
  description: "Used for items where clarification or discussion is required."
- name: "wontfix"
  color: "ffffff"
  description: "Marks issues or PRs that will not be addressed or fixed."
