name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4.1.1
      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: "--check ."
