name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4.1.1
      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: "--check ."
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4.1.1
      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v14.0.0
        with:
          config: ".markdownlint.jsonc"
          globs: |
            docs/*.md
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4.1.1
      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v3.3.2
        with:
          path: ~/.local
          key: poetry
      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1.3.4
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          cache: poetry
      - name: Install linters
        run: poetry install --no-root --only=lint
      - name: Format Python with Ruff
        run: poetry run ruff format .
      - name: Lint Python with Ruff
        run: poetry run ruff .
